global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics

  - job_name: 'monitor-service'
    static_configs:
      - targets: ['monitor:8001']
    metrics_path: /metrics
