global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'proxy-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['proxy-metrics:8000']

