global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics

  # Microservices scraped via published host ports
  # Note: On macOS/Windows with Docker Desktop, host.docker.internal resolves from containers.
  # On Linux, replace with the Docker bridge gateway (often 172.17.0.1) or add extra_hosts.
  - job_name: 'micro-api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: /metrics

  - job_name: 'proxy-metrics'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: /metrics
